### ISSUE TITLE
Circle not centered

### ISSUE THREAD

**Issue by Glennmen** [leshchenko/CircularLayoutManager#4]
I am having an issue with the Recyclerview items not being centered correctly in the circle. Not sure if I am doing something wrong here.

See outer circle
![IMG_20191009_161428](https://user-images.githubusercontent.com/11406433/66489677-4be5b600-eab0-11e9-94e9-ca8e5d2eb356.jpg)

My layout file of outer circle:
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="250dp"
    android:layout_height="350dp">

    <View
        android:id="@+id/sidebarBackground"
        android:layout_width="350dp"
        android:layout_height="match_parent"
        android:layout_marginStart="-150dp"
        android:background="@drawable/circle"
        android:backgroundTint="#DFDFDF" />

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/recyclerviewSources"
        android:layout_width="350dp"
        android:layout_height="match_parent"
        android:layout_marginStart="-150dp" />

</RelativeLayout>
```

CircularRecyclerLayoutManager
```java
CircularRecyclerLayoutManager layoutManager = new CircularRecyclerLayoutManager(5,
                45,
                200,
                0,
                false,
                180,
                true);
```

**Comment by leshchenko** [comment]
@Glennmen Looks strange. Thanks, I'll take a look.

**Comment by Glennmen** [comment]
@leshchenko Is this part correct?
https://github.com/leshchenko/CircularLayoutManager/blob/1637ddc871aa2df59f8bbb987296b9d19763fae1/circularlayoutmanagerlib/src/main/java/com/leshchenko/circularlayoutmanagerlib/CircularRecyclerLayoutManager.kt#L73-L74

I did some searching and it seems that your x & y calculations should be switched:
https://math.stackexchange.com/a/854287
![image](https://user-images.githubusercontent.com/11406433/66553454-6faa0a00-eb4b-11e9-9db0-377da604eaf6.png)

**Comment by leshchenko** [comment]
@Glennmen Please try new version.

**Comment by leshchenko** [comment]
> @leshchenko Is this part correct?
> 
> https://github.com/leshchenko/CircularLayoutManager/blob/1637ddc871aa2df59f8bbb987296b9d19763fae1/circularlayoutmanagerlib/src/main/java/com/leshchenko/circularlayoutmanagerlib/CircularRecyclerLayoutManager.kt#L73-L74
> 
> I did some searching and it seems that your x & y calculations should be switched:
> https://math.stackexchange.com/a/854287
> ![image](https://user-images.githubusercontent.com/11406433/66553454-6faa0a00-eb4b-11e9-9db0-377da604eaf6.png)
Looks like you are right, but I need more time for investigation it in the code as just swapping `sin` and `cos` doesn't help.

**Comment by Glennmen** [comment]
I am going to pull this repo and try to investigate myself for a correct solution, could you reopen this issue?

Btw I haven't tested the new version, will do that first but seeing that cos/sin isn't correct this should still be fixed.

**Comment by leshchenko** [comment]
@Glennmen Fixed in 1.1.5.

**Comment by Glennmen** [comment]
@leshchenko Using v1.1.5 and still having the same issue (not centered).

**Comment by Glennmen** [comment]
@leshchenko I made a branch with changes to the app sample so you can reproduce the bug I am having: https://github.com/Glennmen/CircularLayoutManager/tree/reproduce-off-center

I will try to look into it myself and let you know if I find anything.

**Comment by Glennmen** [comment]
I think the issue is with this line:
https://github.com/leshchenko/CircularLayoutManager/blob/d651375f90ff2b8c3e0bcc52f53432b7cb253272/circularlayoutmanagerlib/src/main/java/com/leshchenko/circularlayoutmanagerlib/CircularRecyclerLayoutManager.kt#L192

`itemWidth` is being calculated on other values and not based on the actual child item size. Because of this the items are being added with a wrong size and looks off-centered.

I added a background color to the view to visualise this.
![IMG_20191010_145252](https://user-images.githubusercontent.com/11406433/66570360-bc064180-eb6d-11e9-86df-19fe7e720c23.jpg)

**Comment by leshchenko** [comment]
@Glennmen Item size calculates depends on layout manager settings, it's need to fit all items in a circle radius and have some free space between items. Could you please create sample project and push it on Github? I think there is issue with xml layout.

**Comment by Glennmen** [comment]
Items not being centered in the item view was a mistake from my end 🤦‍♂️
Item view size being bigger than I wanted is specific to my project I think, so it can remain like it is now. I was able to find a workaround so that I can pass touches outside my item (but still inside the item view) to the window behind it.

I will close this issue, thanks for the support.
